### ISSUE TITLE
Python example not working!

### ISSUE THREAD

**Issue by adityank11** [mgrmtech/fidelius-cli#10]
Hi, I downloaded the repository and tried to run the Python example code. However, I am getting this error:
Traceback (most recent call last):
  File "d:\ABDM\fidelius-cli-main\examples\python\main.py", line 132, in <module>
    main()
  File "d:\ABDM\fidelius-cli-main\examples\python\main.py", line 128, in main
    runExample(stringToEncrypt)
  File "d:\ABDM\fidelius-cli-main\examples\python\main.py", line 76, in runExample        
    requesterKeyMaterial = getEcdhKeyMaterial()
  File "d:\ABDM\fidelius-cli-main\examples\python\main.py", line 29, in getEcdhKeyMaterial
    result = execFideliusCli(['gkm'])
  File "d:\ABDM\fidelius-cli-main\examples\python\main.py", line 17, in execFideliusCli   
    result = subprocess.run(
  File "C:\Users\Aditya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run       
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Aditya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Aditya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
Is there any way, I could fix this?

**Comment by saiki-k** [comment]
Please ensure that JRE 1.8+ is installed, to run the binaries. Run the `fidelius-cli` binary inside the bin folder (examples/bin), in a shell, and ensure there are no errors there.

**Comment by adityank11** [comment]
Yes, I have JRE 1.8+ installed in my laptop. What is the command that I should exactly run? Currently I am running this command to test the python program, please give a step-by-step walkthrough of how to execute this program:

PS D:\ABDM\fidelius-cli-main> python examples/python/main.py

**Comment by saiki-k** [comment]
Please change the `binPath` in `main.py` (line 11 · Add the '.bat' extension) to:
```python
binPath = os.path.join(
    dirname, f'../fidelius-cli-{fideliusVersion}/bin/fidelius-cli.bat'
)
```

Then run the same command as in your comment above. Hopefully, that should fix your issue. Let me know.

PS: We were operating under the assumption that the shell picks the correct binary based on the extension, and it indeed works as intended on the Windows terminal.

**Comment by adityank11** [comment]
Hey, that worked! Thanks for your help!

**Comment by adityank11** [comment]
Hi, I have another question regarding this Python example. Is it possible to separate the encryption and decryption into 2 separate python files where one file will act as the sender of encrypted string and the other file will receive the encrypted string and decrypt it to get the plain text? If yes, what type of approach can I follow?

**Comment by saiki-k** [comment]
You can make a module (say fidelius.py), with all the functions (and imports) as present in main.py, and you can import it wherever/however you want, as per your project's structure.
