### ISSUE TITLE
Decrypted data read as string of OrderedDict in python

### ISSUE THREAD

**Issue by arpitkjain7** [mgrmtech/fidelius-cli#13]
Hi Team,

Thanks for this great library for encrypting and decryting FHIR data. Were we are struggling is when we decrypt the data using the cli python implementation, we are getting results in string of ordereddict. Is there any way we can get it directly as a list of dict. It is really difficult to convert a string of OrderedDict to dict/json format.

Thanks,

**Comment by saiki-k** [comment]
Hi, can you please add more details with your code and a sample output to better demonstrate your issue?

**Comment by saiki-k** [comment]
Please feel free to re-open this issue, if necessary, with requested details.
