### ISSUE TITLE
Not able to execute fidelius-cli bat file on linux server 

### ISSUE THREAD

**Issue by wrehman09** [mgrmtech/fidelius-cli#17]
Hi Team, 
Thank you for making such wonderful library but i am unable to execute bat file from php on linux server. Tried bypassing the batch file and directly called the jar file but it is giving "Could not find or load main class"

Please help

**Comment by saiki-k** [comment]
The .bat file (`fidelius-cli.bat`) is for Windows. For Linux, please use the `fidelius-cli` binary.

**Comment by wrehman09** [comment]
HI @fatman- , Getting below error   java.lang.ArrayIndexOutOfBoundsException at java.lang.System.arraycopy(Native Method) at java.util.Arrays.copyOfRange(Arrays.java:3521) at com.mgrm.fidelius.encryption.EncryptionController.encrypt(EncryptionController.java:28) at com.mgrm.fidelius.FideliusApplication.runCli(FideliusApplication.java:49) at com.mgrm.fidelius.FideliusApplication.main(FideliusApplication.java:107)
![image](https://github.com/mgrmtech/fidelius-cli/assets/16235514/a2c4a833-fb87-4fe5-862a-57be492d8fbd)

**Comment by saiki-k** [comment]
What exactly are you attempting to achieve here? I need at the very least, basic context/details to comprehend the situation surrounding this error message — What is the command that you've used? What is the data that was intended for encryption? What other input parameters were used, and how? — it becomes rather challenging for me to provide you any meaningful assistance without these details.
