### ISSUE TITLE
[Community Announcement] Implemented a native Python version of Fidelius

### ISSUE THREAD

**Issue by sravfeyn** [mgrmtech/fidelius-cli#18]
Hello community,

We have implemented a Python version of this project here https://github.com/dimagi/pyfidelius/pull/1. This enables Python developers to use the encryption scheme implemented in this project without requiring Java in their environments. Please see [README.md](https://github.com/dimagi/pyfidelius/blob/c196b57b823640da9bb0100edf1c0da6f9786081/README.md) for more details.

Feedback is welcome.

**Comment by sravfeyn** [comment]
FYI @fatman- @saisk8 @Ranveer0508

**Comment by saiki-k** [comment]
> Hello community,
> 
> We have implemented a Python version of this project here [dimagi/pyfidelius#1](https://github.com/dimagi/pyfidelius/pull/1). This enables Python developers to use the encryption scheme implemented in this project without requiring Java in their environments. Please see [README.md](https://github.com/dimagi/pyfidelius/blob/c196b57b823640da9bb0100edf1c0da6f9786081/README.md) for more details.
> 
> Feedback is welcome.

Sravan, this is a fantastic development! Once you have completed the integration of X.509 keys, I recommend sharing this update on the [ABDM Dev. Forum](https://devforum.abdm.gov.in/). This will not only provide an opportunity for you to collaborate with integrators who utilize Python in their tech stack but also allow you to test your implementation with their valuable inputs. Great work, and best of luck with your endeavors!
