### ISSUE TITLE
Unable to find the video.

### ISSUE THREAD

**Issue by YeshnaArya** [mgrmtech/fidelius-cli#7]

**Comment by saiki-k** [comment]
The video demonstration of Fidelius CLI in the context of a HIP is currently not a part of this repository.

However, you may access the video through the following sources:
- https://devforum.abdm.gov.in/t/fidelius-cli-a-complete-end-to-end-cryptography-solution/3906/4?u=saiki
- https://www.youtube.com/watch?v=iDcCP9h5hZs
