### ISSUE TITLE
 failed to construct sequence from byte[]: DER length more than 4 bytes: 77 -- error while decryption

### ISSUE THREAD

**Issue by dhavalu903** [mgrmtech/fidelius-cli#8]
here is my response data 

{
    "receiverPrivateKey":"Ceh7oFkd+JsdPZS6MeLGkMdU7iO/7rDl2xwG+p4iOmQ=",
    "receiverNonce":"hvPWpI/LkP0cLYWhj+PiRdzq33UIhQhT0BkY7843C68=",
    "senderPublicKey":"MIIBMTCB6gYHKoZIzj0CATCB3gIBATArBgcqhkjOPQEBAiB/////////////////////////////////////////7TDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHqqqqqqqqYSRShRAQge0Je0Je0Je0Je0Je0Je0Je0Je0Je0Je0JgtenHcQyGQEQQQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0kWiCuGaG4oIa04B7dLHdI0UySPU1+bXxhsinpxaJ+ztPZAiAQAAAAAAAAAAAAAAAAAAAAFN753qL3nNZYEmMaXPXT7QIBCANCAAQnTS40V04mtURhiMheoiJrXGy2nMyfhosToMgpNqKwFnEE536nHEU/TVabRl4K9PV/wkoh7ekfnjDN/Xrmj41i",
    "senderNonce":"AQjD4Bfxz8aGVUY+7qYHb6CvqRyekxexw2O5qghxMRw=",
    "encryptedData":"zQUdNEU00auAxiR8hUm5b42pvwEzslV7241B1M4gZ+N2TJky/mYFJPAJNTqGqm8+4a+Jlr6CCGBlxwdromhRZxIwxBHI5bGAsw2NoqcFlusKwwYkw535HWqhYM9QpS+/xFkmLsz9pIbAeAlQS0WTFpDCnFydeZEmq4uoXMIVCAYOMzU/x1RVefzVPIiPxZxVTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHXFcNd/lYrbYpejzIeBrwTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuH39HdDP2OscIbrPvPSojvSQ1vhB/gFhoWPs2krfq8Y3P4RTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuH4viF/ryTPBAN2bM/ID/ALyewfyrBG/m/D3q9H4jTEFWGVVO0iulTyL1GBb2hJPZXRVW+2dwLvtJEOazn9Nz5sN2IvLSLldqwV7y9DiBCFwcfFG0Hbs+mO6Ac8P+5oXXpaNch+FrTf/63vI/J1Dy+aDDh2W0lK3MwIG0jTbIKc9zpD/WJ/uivgEnxl7XSBqaND3ESlIu9PM/iSkGkaQ4sjf6BC7ayLM2u1rnTqsy5PDN51ih1L3ypz3zWWDDV80OKHOqQMwgESo+fm4fy77t6lUOy2dr740lxaFS0sUhRE9/fRHuRwS8bKje53TjBhQCJaTozM0su+ibrswGgqjKC+D7Z4dleED3RrWara/+9rYWO6hQnzzE1zATh5CnjE024ZcFjQIb4kB1Pb8WElBda2P234Xq/EwpWyyDUcuhOdVdCWgtLsZPWCOfUywixz+yG2iqvP81IJAK6JVjscPLv3y3mWQ9p0CzgEguW9gvf9y8wugrqcop4xuP2tsGomCnyyHHvbgzAZar8yjIGN053vuJYop+FdrURtEt1emFvYcwyUoe410jXPkyr1D92TDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHiyseDkaNNbbTzdXQL9rMHOxUmJhGamvzKcTnSh709fZhPgmKAggOAUvnrWaKVRdyX3edyvHiQ2fk7yuPrHz5oktxaD4QEZOY3h6ppbsbVAnEzfJMMy/X5948DSaE8fdzmiPNGzQtQJXaDQrT2oYOU0e3THuPDnt4qOcFOPG5kPHsnHn+hdqwJn19r8oBlpTcKWsfR4XCveWaFD+fmABDo/sLSpWuxw/io0vo7Mx3EIakSkQaQFTjxDW8Ma/k8Q/rKjAoTeHJJwUJc4aNeO/mkIb+UQzgLfm19vO6+U4TQgr0sNSO08DzvyWVFVLUc9uZ25fyMG8tiUqzAjVMsWOkJ1AwFzPQDG+0Xo4MI5ylP2XdvaMVApEQ/LNv706hLDy4eIb+Au3UgzRwccqkf4Eu1a1W4MkvWXDzWmTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHAstf2a1EubTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHy0LA22i+B7QjJifd5JD5ZZHOxg2V59PMNFf6ntlFnnUjyVVYmC3oB+eI2r4i2uL8MVrCYf/Barp+t/vvE3/3936PRvcNqOduRTettsc+UEh+CN1HGhWmQQiTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHQKKxaA5f3EhgV34fac67sO6s2aE0dJAAo2wYEBriVja9U7UJbUd5dGvnZ+dlN4BtG+KUFMQPaFLQbmZB61EDivydZfdJiDLbImXD2etz7LLS8FNLeDOvbBAk35sMD98dgX1ZVivRmI+J/gSeud9aax4QLNSiREepvz4dJPNsbP3sRIeGQnken9wHxJx1Vog3RMsDO6y7iHkHhsV0gG2VQO7dRrqHFtSj5vjthxgXRUPjbtiC4+kOICcHU11bTxc+oOEKIUKDm2fM2qgow3hJ3Tc+jVjI7ZT+2cJ7o6AQF0B82Yk4S8gOWyy43fRxLZwGzAWZjyEDO3NHXVdvwM9sRCX14FAnbApjbfbIDynKGpe3WvKRk5URdDe858M9Zh364lG4WGVVsF8KHrm3UQ2x50CaqM7nL8yzdiMgwVBLhRyrmwK+4tKDGLf7KwspRgjYYqDQUPEFTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHdFidwoudYo6OhS7i4jt7BbY7W4vk8gmLYMEg8fZqp6v3cR0zbwESbw7vzgIlNK8YQnW9j95RHTzBpisoxwDkNSSOl2cT5A0jyTY0GePo6qtYw8bRYqmG6HuG5fD+th6o5ZJsoLcBx/w0MehVhK6t8RUQ/KZNffbYXYI3pWY/jTrpkWfo0rJmuW+iNkTbGPMKow1i/Xi0kh16Cd6flpD+TwJb4M+l5hGrqXnQ2hVKAhqUWYZbuf7HSplSM/yTGR3v3Z5A2wiSYo1uvMZ01j8BGIdX5MMozO0+sIz0+GVLXQs+/aIAC4A8O3l9STH9vHuPeUx0m/mbdzeOJFRA9tsBU8o842CzIjT8zq5XDAfcHG5NfR0eLVHJRFQZTvov18qAQ8+ytWOok2OW8JTuBJ7TrOcpw9XOpp2Ew0LcokHMtF6owNVyjBlqfoE7mO383+E5Au/2Z+120LBGrX/angR0ksVKOMffCLorBB8uXJG5oAyc6NAVDHuRcmpAi7N6+no4LvUwXXNK6Bb2LfvLCwgqpECPJWGzc1VOeXQwQXkV/rIIfo16Ox6XOnhJSFaXgW92+rodGvgtiqqx9KyM0cLiGrY6Ew6c5toGBRCTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHE1xSNhLiSr6/L7xq93MXBw/Kz1AFHCCwqAap7hsUhyTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHNtRZREwAitu6GZqrXuM2kOx1jsnUvI4GKwQjEqVV0d/6yx11phqTW7UYUSiJq/cRY5TPc3ze8H1yZ/AeIGOGZSUTUGXTuzA5ctXogLANBN2Pmc/DFY9470Xfmy+YOlJcPCseUdK6jOGVu/yzE6IUsfgTdNDDjV34hd/6BFXuNyQZDSOj0twhFGJUSL/pUxA4HRa9FALbMO6c/9iDTTXKYtoTtymLVvfa0AJ+/eLQruyiaDK19Uqikrj+ll71uNFcwiEjHTyu9gl1Ogq4OchRbKNI6FKhYCi+6/3W3qBAPbN1otehl3/unqIh/Fwb7O2dquY6wNQIbs2eJBpB4BDjYidGyRi6WjqFGko0kCQRrnpL4pa/5P7FgljX5cqeGisXH5JmF4QNrI3kHQOQQJi6yGVZHrcXA+AXOpOf5x1IHROUyQ9fTo/5URtxJUakCm+sd0NgKOaoqrRHLBQnYXhucgkMC/7dASCW1Ky14Uepx47O/pk7tTGHNe/u7ApAnuId/z4XRJN3wL5QQpA7sL+Cb6jjQTDNEpUTHQoQUJMHLrErGJyHg89uy71MyuHZTIZIa/m93fX5Ydyh6eC/9JeGCcZ1Zrx/JoVNLWMJPmP1Jrto8FMpAPtxnA5dqTexFhBoGu8bfe7kk57VJkolKGCRW4="
}

**Comment by saiki-k** [comment]
This is a data flow issue — probably because of an incorrect public key/nonce — and not an issue with `fidelius-cli`. Please post this to the ABDM Sandbox Dev. Forum with more details and the sequence of steps that led you to this error.
