### ISSUE TITLE
Why is the public key 64 bytes even though the key material for Curve25519 should be just 32 bytes. And why is there a need of X509PublicKey?

### ISSUE THREAD

**Issue by satwik-tanwar** [mgrmtech/fidelius-cli#9]

**Comment by saiki-k** [comment]
### Why is the public key 64 bytes?

In this implementation, the public keys that are generated and sent forward, are uncompressed EC public keys (of Curve25519). They include both the X and Y coordinates of the EC point (corresponding to the public key), each 32 bytes in length. IIRC, this has been a standard ABDM requirement from the sandbox's inception. From what I read, the protocol, and subsequently the algorithm only use the X coordinate (32 bytes in length) internally, in all operations including the public key.

### Why is there a need of X509PublicKey?

Some HIU implementations at the time of this project's development (including Sandbox's HIU interface) only accepted the public keys in X509 format. This has been discussed as a part of the new documentation panel, and we landed on a soft recommendation against its use. The following is a note from the FideliusCLI section in the new documentation.
> It is generally recommended to use the `publicKey` field, which represents the base64 encoding of the uncompressed EC public key, for all encryption and decryption operations. However, it is important to note that certain HIUs only accept the public key in the base64-encoded X.509 format, specifically within the key material sent by the HIP, before decryption.

**Comment by satwik-tanwar** [comment]
Thanks for replying!

I am trying to implement the encryption process direly in Node.Js, I couldn't find any method that generates uncompressed keys for Curve25519, all the methods outputs only the x-coordinates.

I was encrypting sample data using public key generated fron FideliusCLI which was successful.

Then, I tried to decrypt that data using FideliusCLI. But it was unsuccessful because FideliusCLI was expecting either a 64 byte public key or one in x509 format.

Would it be possible to update the cli such that it can work with 32 bytes received keys

**Comment by saiki-k** [comment]
We have been on the same journey of trying to implement the documentation standard completely in NodeJS, however there are certain esoteric differences (as you mention) that — I'm fairly certain — can't be reliably ported over to NodeJS. We were still unsatisfied with the lack of a standard abstract implementation for encryption/decryption, and that is why we made `fidelius-cli`.

I would suggest that you look at the NodeJS example in the `examples` folder. You can use `fidelius-cli` by invoking it as a subprocess in your NodeJS solution.

**Comment by satwik-tanwar** [comment]
Thanks! Will look into it.
